### PR TITLE
Beacon Hill Essay

### PR DESCRIPTION
**Pull request by tuhaze**

### CODE REVIEW

**Comment by garrettdashnelson** [comment]
@tuhaze In the Markdown frontmatter, you need to delete those two empty spaces just after and before the opening and closing `---` lines.

Example:

```
---

title: This won't work

---
```

```
---
title: This will work
---
```

**Comment by tuhaze** [comment]
Sorry! I have fixed the spacing, not sure if the new one came through

**Comment by garrettdashnelson** [comment]
One last change ... and indicative of just how fragile code can be! The first `---` needs to be the _very_ first line of the file, which means you need to delete the first two blank lines. @tuhaze

**Comment by tuhaze** [comment]
Third time's the charm right?

**Comment by garrettdashnelson** [comment]
Looks great! 😄

**Pull request merged**
